spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres



  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/db-changelog-master.xml
    default-schema: public
    contexts: migrated

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public


bot:
  name: Eeessstbot
  token: 6001137020:AAGnSQR7Srwr16ahNJf56lWs2KPLOIvx8Jg
  admin: 1096527924